### ISSUE TITLE
Migrate Open Match web/docs to this repo

### ISSUE THREAD

**Issue by thisisnotapril** [googleforgames/open-match-docs#1]

**Comment by jeremyje** [comment]
https://github.com/googleforgames/open-match-docs/pull/7
https://github.com/googleforgames/open-match-docs/pull/6
https://github.com/googleforgames/open-match-docs/pull/5
https://github.com/googleforgames/open-match-docs/pull/4
https://github.com/googleforgames/open-match-docs/pull/2

Are the merges to fix this issue.
