### ISSUE TITLE
Slack invite link is no longer active

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/open-match-docs#110]
At the bottom of https://open-match.dev/site/ there is a link to join the open match Slack ("Read more..." which is a terrible name for this call to action). Clicking on it takes me to a page that says:

> This invite link is no longer active.
> 
> Please check with the person who shared it with you to see if there's a new link available.

Prior to KubeCon we should fix the link so that new folks can join the slack community.

**Comment by yfei1** [comment]
The Read more... is provided by the docsy and there's no way to override it :(. Working on a fix to update the link!

**Comment by yfei1** [comment]
#116 overrides the Readmore text and should looks much better.
