### ISSUE TITLE
Getting Started Guide should be explicity that HELM install will not work

### ISSUE THREAD

**Issue by sisso** [googleforgames/open-match-docs#213]
If you install open match using helm, if you follow the steps of Getting Started the demo will not run because will not be able to resolve the DNS, as the "Install with Helm" will make a deployment using "my-release", causing the expected DNS "open-match-frontend.open-match.svc.cluster.local" be "open-match-frontend.my-release.svc.cluster.local".

My suggestion is to update "install with Helm" to use the correct release name or add a note in "Getting Started" to use the manual installation.

**Comment by syntxerror** [comment]
I'll run through this when I get that chance but during the release when running through the steps I haven't encountered it. I'll take a look after the weekend. Thanks for bringing this to our attention

**Comment by syntxerror** [comment]
@sisso #219 has been submitted for the fix. Would you mind confirming the steps for the running the demo work for you
![image](https://user-images.githubusercontent.com/38893532/114634333-4a421300-9c90-11eb-8512-d26d9a3a1b47.png)

**Comment by sisso** [comment]
@syntxerror Yeah, lgtm. I followed the example from zero copying your changes and I was able to run the demo.
