### ISSUE TITLE
403 forbidden when kubectl apply

### ISSUE THREAD

**Issue by kigawas** [googleforgames/open-match-docs#218]
https://open-match.dev/install/v1.2.0/yaml/01-open-match-core.yaml looks like down.

```
$ kubectl apply --namespace open-match \
  -f https://open-match.dev/install/v1.2.0/yaml/01-open-match-core.yaml
error: unable to read URL "https://open-match.dev/install/v1.2.0/yaml/01-open-match-core.yaml", server reported 403 Forbidden, status code=403
```

**Comment by syntxerror** [comment]
When looking at the documentation it looks like it is updated with the 1.2.0-rc.1 tag. Please try the command again but substitute 1.2.0 -> 1.2.0-rc.1
