### ISSUE TITLE
Step 1 - Build your own Game Frontend: docker build fails. 

### ISSUE THREAD

**Issue by kemurayama** [googleforgames/open-match-docs#247]
Hi, 

According to the document, `docker build` looks working successfully. 

Actually, it doesn't work in `go build` section of its Dockerfile because the line `replace open-match.dev/open-match v0.0.0-dev => ../../../` in the `go.mod` of the frontend folder.

**Comment by syntxerror** [comment]
Hi @kemurayama 
Yes, we are aware of this and are looking to correct this in the all previous and future releases soon. If you haven't figured it out, with the go.mod files for the tutorials, please substitute this line:
`open-match.dev/open-match v0.0.0-dev`
with:
`open-match.dev/open-match v1.3.0`
or the release branch you are using.

Hope this helps.

**Comment by kemurayama** [comment]
Hi @syntxerror, 

Good !! I am glad to know that it will be corrected.  As far as I tried, the Dockerfile also needs `RUN go mod download open-match.dev/open-match` in line 4.

I am really looking forward to seeing the updated document.

```Dockerfile
FROM golang:alpine as go
WORKDIR /app
ENV GO111MODULE=on

COPY . .
RUN go mod download open-match.dev/open-match
RUN go build -o frontend .

CMD ["/app/frontend"]
```

Thanks.
