### ISSUE TITLE
Outdated configmap indication in installation instructions

### ISSUE THREAD

**Issue by Kaszanas** [googleforgames/open-match-docs#297]
Installation instructions for YAML based workflows contain slight errors when mentioning the configmap that is supposed to be overriden.

Instructions explicitly show a table of `ContainerCreating` with abbreviated `om-frontend`, which is currently `open-match-frontend`, when running release `1.7`.

Additionally, the instructions mention `om-configmap-override`, while all of the yaml files expect `open-match-configmap-override`.

**Comment by joeholley** [comment]
TYVM for the heads up.  I included this in the update I had to do to the installation guide to bump the tested k8s version in https://github.com/googleforgames/open-match-docs/pull/301

**Comment by kemurayama** [comment]
Seems it has been fixed. in #301
