### ISSUE TITLE
Installation docs: why suggest enabling optional APIs?

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/open-match-docs#83]
From https://development.open-match.dev/site/docs/installation/

The instructions for creating a GKE Cluster have:

```bash
# Enable optional GCP services for security hardening
gcloud services enable containeranalysis.googleapis.com
gcloud services enable binaryauthorization.googleapis.com
```

which seem superfluous. The command to create the cluster doesn't enable binauthz, nor does the guide explain how you would take advantage of the binary authorization features in GKE (e.g. how do you sign the open match system containers?).

**Comment by sawagh** [comment]
Removed this suggestion now -
https://github.com/googleforgames/open-match-docs/commit/765e1580d27f41d827f3e88692c6ac9ef891ecd1
