### ISSUE TITLE
Installation docs: Require role binding?

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/open-match-docs#84]
From https://development.open-match.dev/site/docs/installation/:

Is this still necessary?

```
# Create a cluster role binding (if using gcloud on Linux or OSX)
kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user `gcloud config get-value account`

# Create a cluster role binding (if using gcloud on Windows)
for /F %i in ('gcloud config get-value account') do kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user %i

# Create a cluster role binding (if using minikube)
kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --serviceaccount=kube-system:default
```

Starting with Kubernetes 1.12, I don't think you need to do this any longer (I removed it from the Agones instructions when we switched to using 1.12). Please verify and remove these steps if they aren't needed, as it greatly simplifies the install instructions if people don't need to understand RBAC before going through the getting started guide.

**Comment by sawagh** [comment]
This is fixed by https://github.com/googleforgames/open-match-docs/commit/765e1580d27f41d827f3e88692c6ac9ef891ecd1

We still need to address the issue with specifying the min version which after this commit is even more important.
