### ISSUE TITLE
Matchmaking using Open Match: add a diagram for life of a request?

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/open-match-docs#88]
From https://development.open-match.dev/site/docs/guides/matchmaker/:

The flow in life of a request is a bit confusing because there are a lot of actors and it isn't clear how much happens synchronously or asynchronously. A sequence diagram would be super useful to make this clearer.

In particular, I _think_ that the game front end and director are making async calls (unrelated to each other) but that both have to happen before a match can be generated. This means that people need to understand how often a directory should be making calls to make matches happen quickly.

**Comment by yfei1** [comment]
Closed by #115
